dofile(minetest.get_modpath("army").."/chainlink.lua")
dofile(minetest.get_modpath("army").."/camouflage.lua")
dofile(minetest.get_modpath("army").."/sandbag.lua")
dofile(minetest.get_modpath("army").."/barbedwire.lua")
dofile(minetest.get_modpath("army").."/light.lua")
dofile(minetest.get_modpath("army").."/airdrop.lua")
dofile(minetest.get_modpath("army").."/ration.lua")
print("[Army] Army Mod Fully Loaded!")
